Updated to git 1.7.7.2

diff --git a/bin/git-folder/git-sh-setup b/bin/git-folder/git-sh-setup
--- a/bin/git-folder/git-sh-setup
+++ b/bin/git-folder/git-sh-setup
@@ -38,9 +38,15 @@ git_broken_path_fix () {
 }
 
 
-die() {
-	echo >&2 "$@"
-	exit 1
+die () {
+	die_with_status 1 "$@"
+}
+
+die_with_status () {
+	status=$1
+	shift
+	echo >&2 "$*"
+	exit "$status"
 }
 
 GIT_QUIET=
@@ -137,6 +143,13 @@ cd_to_toplevel () {
 		echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
 		exit 1
 	}
+}
+
+require_work_tree_exists () {
+	if test "z$(git rev-parse --is-bare-repository)" != zfalse
+	then
+		die "fatal: $0 cannot be used without a working tree."
+	fi
 }
 
 require_work_tree () {
